on: push

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
    
      - name: 📂 Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.ititans.com
          username: zainjaved@ititans.com
          password: ${{ secrets.FTP_SECRET }}
          local-dir: ./   # This is the directory containing your code
          remote-dir: frp.ititians.com/public_html   # This is the target directory on the FTP server

        
